import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  imagem:{
    width:400,
    height:300,
    position:'absolute'
  },
  icones:{
    flexDirection:'row',
    marginTop:60,
    justifyContent:'flex-end',
    width:370,
  },
  icone1:{
    justifyContent:'center',
    backgroundColor:'#faf8d4',
    borderColor:'#c89a65',
    color:'#c89a65',
    borderWidth:2,
    borderRadius:15,
    alignItems:'center',
    padding:5,
  },
  icone2:{
    borderColor:'#c89a65',
    borderWidth:2,
    color:"#5b3000",
    borderRadius:21,
    backgroundColor:'#ece3b8',
    padding:3,
  },
  box:{
    backgroundColor:'#faf8d4',
    borderRadius:22,
    height:500,
    width:400,
    paddingLeft:30,
    paddingRight:30,
    flexDirection:'row',

  },
  imagem2:{
    width:40,
    height:40,
  },
  mensagem:{  
    flex:3,
    borderColor:'#7fa9c7',
    borderWidth:2,
    borderRadius:20, 
    padding:20,
    backgroundColor:'#faf8d4',
    marginTop:-35,
    width:50
  },
  icone4:{
    flex:3,
    justifyContent:'flex-end',
    backgroundColor:'#faf8d4',
    borderColor:'#8ec46e',
    borderWidth:2,
    borderRadius:20,
  },
  texto1:{
    color:'#5b3000',
    fontFamily:'Brixton-Regular',
    fontSize:25,
  },
  texto2:{
    color:'#5b3000',
    fontFamily:'Brixton-Regular',
    fontSize:20,
  }, 
  icone5:{
    backgroundColor:'#faf8d4',
    borderColor:'#7fa9c7',
    borderWidth:2,
    borderRadius:20,
    color:'#c89a65',
  },
  icone6:{
    backgroundColor:'#faf8d4',
    borderColor:'#8ec46e',
    borderWidth:2,
    borderRadius:20,
    color:'#725431',
  },
})